"""Init tables

Revision ID: 863110f6881a
Revises: 
Create Date: 2025-05-02 00:47:49.181286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '863110f6881a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('author',
    sa.Column('id', sa.Integer(), nullable=False, comment='Идентификатор автора'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Полное имя автора'),
    sa.Column('bio', sa.String(length=1000), nullable=True, comment='Биография автора'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_author_lower_name', 'author', [sa.literal_column('lower(name)')], unique=True)
    op.create_table('genre',
    sa.Column('id', sa.Integer(), nullable=False, comment='Идентификатор жанра'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Название жанра'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('ix_genre_lower_name', 'genre', [sa.literal_column('lower(name)')], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False, comment='Идентификатор пользователя'),
    sa.Column('username', sa.String(), nullable=False, comment='Уникальный юзернейм пользователя'),
    sa.Column('email', sa.String(), nullable=False, comment='Уникальная электронная почта пользователя'),
    sa.Column('hashed_password', sa.String(), nullable=False, comment='Хэш пароля пользователя'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('publication_year', sa.Integer(), nullable=False),
    sa.Column('average_rating', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['author.id'], onupdate='cascade', ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_book_author_id'), 'book', ['author_id'], unique=False)
    op.create_table('book_genre',
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], onupdate='cascade', ondelete='cascade'),
    sa.ForeignKeyConstraint(['genre_id'], ['genre.id'], onupdate='cascade', ondelete='cascade'),
    sa.PrimaryKeyConstraint('book_id', 'genre_id')
    )
    op.create_table('ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('review', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], onupdate='cascade', ondelete='cascade'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], onupdate='cascade', ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ratings')
    op.drop_table('book_genre')
    op.drop_index(op.f('ix_book_author_id'), table_name='book')
    op.drop_table('book')
    op.drop_table('user')
    op.drop_index('ix_genre_lower_name', table_name='genre')
    op.drop_table('genre')
    op.drop_index('ix_author_lower_name', table_name='author')
    op.drop_table('author')
    # ### end Alembic commands ###
